name: Minio Tests
on: [push, pull_request,repository_dispatch]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

jobs:
  # TODO: significantly reduce this -- it currently dups httpfs tests which need data; these only need enough for crednetial tests
  minio-tests:
    name: Minio Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        duckdb_version: [ '<submodule_version>' ]
    env:
      S3_TEST_SERVER_AVAILABLE: 1
      DUCKDB_S3_ENDPOINT: duckdb-minio.com:9000
      DUCKDB_S3_USE_SSL: false
      GEN: ninja
      VCPKG_TARGET_TRIPLET: x64-linux
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      DONT_STATIC_LINK_DUCKDB: 1 # fixes oom while linking
      CORE_EXTENSIONS: "parquet;json;tpch"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: Checkout DuckDB to version
        if: ${{ matrix.duckdb_version != '<submodule_version>'}}
        run: |
          cd duckdb
          git checkout ${{ matrix.duckdb_version }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Ninja
        shell: bash
        run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

      - name: Setup Ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ${{ github.job }}
          save: ${{ github.ref == 'refs/heads/main' || github.repository != 'duckdb/duckdb' }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.1
        with:
          vcpkgGitCommitId: 5e5d0e1cd7785623065e77eff011afdeec1a3574

      - name: Build
        shell: bash
        run: make

      - name: Start S3/HTTP test server
        shell: bash
        run: |
          ./scripts/install_and_run_httpfs_s3_test_server.sh

      - name: Write AWS credentials file
        shell: bash
        run: |
          ./scripts/create_minio_credential_file.sh

      - name: Test
        shell: bash
        run: |
          make test

      - name: Run Env tests
        shell: bash
        env:
          DUCKDB_AWS_TESTING_ENV_AVAILABLE: 1
          AWS_ACCESS_KEY_ID: duckdb_env_testing_id
          AWS_SECRET_ACCESS_KEY: duckdb_env_testing_key
          AWS_DEFAULT_REGION: duckdb_env_testing_region
        run: |
          ./build/release/test/unittest "*/test/sql/env/*"
